# DB
spring.jpa.database=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
# MyBatis
mybatis.mapper-locations=classpath*:/mapper/*.xml
# typeHandler
mybatis.type-handlers-package=com.aceward.usermanagement.dao.common.UUIDTypeHandler
# Log level
logging.level.com.aceward=debug
# スネークケースをキャメルケースに変換する
mybatis.configuration.map-underscore-to-camel-case=true
# DTOのパッケージ指定
mybatis.type-aliases-package=com.aceward.usermanagement.dao.domain
